### ISSUE TITLE
name of czmq.h is diferent on my system

### ISSUE THREAD

**Issue by grindhold** [jordan-bonecutter/vmq#5]
in order to get vmq to work i had to rename references to `czmq.h` to `zmq.h`. I am on debian testing.
Is there a simple way to fix this problem? What system has vmq been developed on initially?

**Comment by jordan-bonecutter** [comment]
There are two different versions of the zmq api, the low level api (defined in `zmq.h`) and the high level api (`czmq.h`). Since `vmq` uses the low level api I should use `zmq.h`. Fixed in 38f8b49
